In [1]:
import numpy as np

In [3]:
A1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
A2 = np.random.random((3,3))

In [4]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
A2

array([[0.27456192, 0.96428552, 0.17671957],
       [0.44153624, 0.36484981, 0.62119913],
       [0.38233988, 0.33235034, 0.72830405]])

In [41]:
E = np.eye(3)

In [42]:
E

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
A4 = np.zeros((5,5))

In [9]:
A4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
A1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.transpose(A1)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [12]:
np.linalg.det(A1)

-9.51619735392994e-16

In [14]:
np.linalg.matrix_rank(A1)

2

In [15]:
np.linalg.det(A2)

-0.0635081261214214

In [16]:
np.linalg.matrix_rank(A2)

3

In [17]:
A5 = np.array([[7,4],[5,3]])

In [19]:
A6 = np.linalg.inv(A5) # обратная матрица

In [20]:
A5@A6

array([[1., 0.],
       [0., 1.]])

In [24]:
A7 = np.linalg.inv(A1)

In [26]:
A1 @ A7 # для А1 нет обратной матрицы

array([[ 0. ,  1. , -0.5],
       [ 0. ,  2. , -1. ],
       [ 0. ,  3. ,  2.5]])

In [27]:
A8 = np.array([[-1,-6],[2,6]])

In [28]:
np.linalg.eigvals(A8) # собственные значения

array([2., 3.])

In [29]:
np.linalg.eig(A8) # собственные векторы

(array([2., 3.]),
 array([[-0.89442719,  0.83205029],
        [ 0.4472136 , -0.5547002 ]]))

In [30]:
res = np.linalg.eig(A8)

In [34]:
res2 = res[1]

In [35]:
res2

array([[-0.89442719,  0.83205029],
       [ 0.4472136 , -0.5547002 ]])

In [37]:
res3 = np.transpose(res2)

In [38]:
res3[0]

array([-0.89442719,  0.4472136 ])

In [39]:
res3[1]

array([ 0.83205029, -0.5547002 ])